// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_DCKBRxmW2",
    "aws_user_pools_web_client_id": "30d360lpigrltqamdtrp88714n",
    "aws_content_delivery_bucket": "eventhubnat-20181109171628--hostingbucket",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://eventhubnat-20181109171628--hostingbucket.s3-website-us-east-1.amazonaws.com"
};


export default awsmobile;
